title: ğ–ˆğ–ğ–‡ğ–Šğ–—ğ–Œğ–šğ–—ğ–šğŸ’€~$
show_downloads: false
show_repo: false
theme: jekyll-theme-hacker

gems:
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

socialIcons:
    - name: discord
      url: "cyber_guru#9217"
    - name: twitter
      url: "https://twitter.com/cyberguru"
    - name: github
      url: "https://github.com/Cyberguru1"
