title: ğ–ˆğ–ğ–‡ğ–Šğ–—ğ–Œğ–šğ–—ğ–šğŸ’€~$
show_downloads: false
show_repo: false
theme: jekyll-theme-hacker

description: "Hamza's Blog"
author:
  name: "cyb3guru"
  email: "hamzasaidu34@gmail.com"
  url: "https://blog.cyb3guru.tech"

gems:
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

socialIcons:
    - name: discord
      url: "cyber_guru#9217"
    - name: twitter
      url: "https://twitter.com/cyberguru"
    - name: github
      url: "https://github.com/Cyberguru1"
